name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest

    services:  
      postgres_db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: root_user
          POSTGRES_PASSWORD: root_secret
          POSTGRES_DB: bank_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U root_user -d bank_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5
    
    steps:
    - uses: actions/checkout@v4

    - name: List files for debugging
  # This shows you exactly where you are and what folders exist
      run: |
        pwd
        ls -R

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.25
      id: go
    
    - name: Install golang-migrate
      run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

    - name: Wait for Postgres
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        until pg_isready -h localhost -p 5432 -U root_user; do
          echo "Waiting for postgres..."
          sleep 2
        done
    
    - name: Run migrations
      run: |
        export PGPASSWORD=root_secret
        psql -h localhost -U root_user -d bank_db -f ./sql/schema/schema.sql

    - name: Test
      run: make test
